name: Bug Report
description: Report a bug or incorrect behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: command
    attributes:
      label: Command
      description: Which fcoreutils command is affected?
      placeholder: "e.g., fwc, fcut, fsha256sum"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create a test file: `echo "hello world" > test.txt`
        2. Run: `fwc -l test.txt`
        3. Compare with: `wc -l test.txt`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen (include GNU coreutils output if applicable).
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of the command with `--version`, or `cargo install` version."
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context (logs, file samples, environment details).
