name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New command implementation
        - New flag/option for existing command
        - Performance improvement
        - Other enhancement
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Related Command
      description: Which command does this relate to (if any)?
      placeholder: "e.g., fwc, fcut, or 'new: ftail'"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, examples, or references.
